SELECT * FROM PEDIDO

CREATE FUNCTION FAZER_PEDIDO(INT , INT , VARCHAR , INT) RETURN VOID AS $$
DECLARE
	COD_FORNECEDOR INT;
	VALOR_LIVRO REAL;

BEGIN
	SELECT COD_FORNECEDOR INT COD_FORNECEDOR FROM FORNECEDOR WHERE NOME_FORNECEDOR ILIKE $3;
	SELECT VALOR_UNITARIO INTO VALOR_LIVRO FROM LIVRO WHERE COD_LIVRO = $2;

	INSERT INTO PEDIDO VALUES (COD_PEDIDO , COD_FORNECEDOR , CURRENT_DATE , 'NOW',VALOR_L * QUANTIDADE_VENDIDA,QUANTIDADE_VENDIDA);
	INSERT INTO ITEM_PEDIDO VALUES ( COD_LIVRO , COD_PEDIDO , QUANTIDADE_VENDIDA , QUANTIDADE_VENDIDA * VALOR_LIVRO)

	UPDATE LIVRO SET QUANT_ESTOQUE = QUANT_ESTOQUE - QUANTIDADE_VENDIDA WHERE COD_LIVRO = COD_LIVRO;
END;
$$ LANGUAGE 'PLPGSQL';

SELECT * FROM PEDIDO
SELECT * FROM ITEM_PEDIDO
SELECT * FROM LIVRO

-- COMPLEMENTAR EXERCICIO 1
