-- QUESTÃO 1

SELECT NOME , DT_NASC FROM HOSPEDE ORDER BY NOME ASC , DT_NASC DESC

-- QUESTÃO 2

SELECT NOME_CAT "Categoria" FROM CATEGORIA ORDER BY NOME_CAT ASC

-- QUESTÃO 3

-- Usando NATURAL JOIN

SELECT NUM, VALOR_DIA FROM CATEGORIA NATURAL JOIN APARTAMENTO ORDER BY VALOR_DIA DESC

-- Usando INNER JOIN

SELECT NUM , VALOR_DIA FROM CATEGORIA INNER JOIN APARTAMENTO ON
	CATEGORIA.COD_CAT = APARTAMENTO.COD_CAT ORDER BY VALOR_DIA DESC

-- Usando PRODUTO CARTESIANO

SELECT NUM , VALOR_DIA FROM CATEGORIA , APARTAMENTO 
	WHERE CATEGORIA.COD_CAT = APARTAMENTO.COD_CAT ORDER BY VALOR_DIA DESC

-- QUESTÃO 4

SELECT NOME_CAT FROM CATEGORIA WHERE COD_CAT IN 
	(SELECT COD_CAT FROM APARTAMENTO NATURAL JOIN CATEGORIA 
		GROUP BY COD_CAT HAVING COUNT(*) = 1)

-- QUESTÃO 5		

SELECT NOME , EXTRACT(MONTH FROM DT_NASC) "Mês de nascimento" , EXTRACT(YEAR FROM DT_NASC) "Ano de nascimento" FROM HOSPEDE
	ORDER BY AGE(CURRENT_DATE,DT_NASC) DESC ,
	NOME ASC

-- QUESTÃO 6

SELECT NOME , NUM "Apartamento" , COUNT(*) "Hospedagens" FROM HOSPEDAGEM
	NATURAL JOIN HOSPEDE
	NATURAL JOIN APARTAMENTO
	GROUP BY NUM , NOME
	
-- QUESTÃO 7

SELECT NOME_CAT FROM CATEGORIA WHERE CHARACTER_LENGTH(NOME_CAT) > 15
SELECT NOME_CAT FROM CATEGORIA WHERE LENGTH(NOME_CAT) > 15

-- QIESTÃO 8

-- Usando NATURAL JOIN

SELECT DISTINCT NUM , NOME_CAT FROM HOSPEDAGEM 
	NATURAL JOIN APARTAMENTO 
	NATURAL JOIN CATEGORIA 
	WHERE EXTRACT(YEAR FROM DT_ENTRADA) = 2017

-- Usando INNER JOIN's

SELECT DISTINCT APARTAMENTO.NUM , NOME_CAT FROM HOSPEDAGEM INNER JOIN APARTAMENTO
	ON HOSPEDAGEM.NUM = APARTAMENTO.NUM
	INNER JOIN CATEGORIA
	ON APARTAMENTO.COD_CAT = CATEGORIA.COD_CAT
	WHERE EXTRACT(YEAR FROM DT_ENTRADA) = 2017

-- QUESTÃO 9 - INVÁLIDA

-- QUESTÃO 10

CREATE TABLE FUNCIONARIO (
	COD_FUNC INT NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	DT_NASC DATE,
	SALARIO FLOAT NOT NULL
)

-- ADICIONANDO COLUNA E CONSTRAINT DE CHAVE ESTRANGEIRA PARA HOSPEDAGEM - FUNCIONARIO

ALTER TABLE HOSPEDAGEM
	ADD COLUMN COD_FUNC INT NOT NULL 
	DEFAULT 1

ALTER TABLE HOSPEDAGEM
	ADD CONSTRAINT COD_FUNC
	FOREIGN KEY (COD_FUNC)
	REFERENCES FUNCIONARIO(COD_FUNC)

-- ADICIONANDO COLUNA E CONSTRAINT DE CHAVE ESTRANGEIRA PARA RESERVA - FUNCIONARIO

ALTER TABLE RESERVA
	ADD COLUMN COD_FUNC INT NOT NULL
	DEFAULT 1
	
ALTER TABLE RESERVA
	ADD CONSTRAINT COD_FUNC
	FOREIGN KEY (COD_FUNC)
	REFERENCES FUNCIONARIO(COD_FUNC)

-- QUESTÃO 11

SELECT NOME , SALARIO + COUNT(*) * 10 "Reajustado" FROM HOSPEDAGEM
	NATURAL JOIN FUNCIONARIO
	NATURAL JOIN APARTAMENTO
	NATURAL JOIN CATEGORIA
	GROUP BY COD_FUNC , NOME , SALARIO
	
-- QUESTÃO 12

SELECT NOME_CAT , NUM FROM CATEGORIA NATURAL JOIN APARTAMENTO
	ORDER BY NOME_CAT ASC , NUM ASC

-- QUESTÃO 13

SELECT NOME_CAT , COALESCE(CAST(NUM AS VARCHAR),'Não possui apartamento') as "Apartamento"
	FROM CATEGORIA LEFT OUTER JOIN APARTAMENTO
	ON APARTAMENTO.COD_CAT = CATEGORIA.COD_CAT
	ORDER BY NOME_CAT ASC , NUM ASC


-- QUESTÃO 14

SELECT DISTINCT NOME FROM FUNCIONARIO
WHERE COD_FUNC IN
(SELECT COD_FUNC FROM HOSPEDAGEM
	NATURAL JOIN FUNCIONARIO
	NATURAL JOIN APARTAMENTO
	NATURAL JOIN CATEGORIA
	WHERE COD_HOSP IN (SELECT COD_HOSP FROM HOSPEDE WHERE UPPER(NOME) LIKE 'MARLYSSON%')
	OR UPPER(NOME_CAT) LIKE 'EXECUTIVO'
UNION
SELECT COD_FUNC FROM RESERVA
	NATURAL JOIN FUNCIONARIO
	NATURAL JOIN APARTAMENTO
	NATURAL JOIN CATEGORIA
	WHERE COD_HOSP IN (SELECT COD_HOSP FROM HOSPEDE WHERE UPPER(NOME) LIKE 'MARLYSSON%')
	OR UPPER(NOME_CAT) LIKE 'EXECUTIVO') ORDER BY NOME ASC

-- QUESTÃO 15

SELECT COD_HOSPEDAGEM FROM HOSPEDAGEM
	NATURAL JOIN CATEGORIA
	NATURAL JOIN APARTAMENTO
	NATURAL JOIN HOSPEDE
	WHERE VALOR_DIA = (SELECT MAX(VALOR_DIA) FROM CATEGORIA)
	AND DT_NASC = (SELECT MIN(DT_NASC) FROM HOSPEDE)

-- QUESTÃO 16 -- FALTA

-- QUESTÃO 17

SELECT NOME FROM HOSPEDAGEM 
	NATURAL JOIN HOSPEDE
	NATURAL JOIN APARTAMENTO
	NATURAL JOIN CATEGORIA

SELECT COD_CAT FROM APARTAMENTO WHERE NUM IN ( SELECT DISTINCT NUM FROM HOSPEDAGEM WHERE EXTRACT(YEAR FROM DT_ENTRADA) = 2017)

-- QUESTÃO 18 -- FALTA
	
-- QUESTÃO 19

SELECT NOME,DT_NASC,MAX(VALOR_DIA) FROM FUNCIONARIO
	NATURAL JOIN RESERVA
	NATURAL JOIN APARTAMENTO
	NATURAL JOIN CATEGORIA
	GROUP BY NOME , DT_NASC
		
-- QUESTÃO 20

SELECT NOME , COUNT(*)"Hospedagens" FROM HOSPEDAGEM
	NATURAL JOIN HOSPEDE
	GROUP BY NOME


-- QUESTÃO 21

SELECT NOME, DT_ENTRADA, DT_SAIDA , EXTRACT(DAY FROM AGE(DT_SAIDA,DT_ENTRADA)) * VALOR_DIA "Preço total" FROM HOSPEDAGEM
	NATURAL JOIN HOSPEDE
	NATURAL JOIN APARTAMENTO
	NATURAL JOIN CATEGORIA 
	WHERE DT_SAIDA IS NOT NULL
	GROUP BY NOME , DT_ENTRADA, DT_SAIDA , VALOR_DIA