CREATE TABLE CLIENTE(
    COD_CLI INT NOT NULL PRIMARY KEY,
    NOME VARCHAR
)

CREATE TABLE LIVRO(
    COD_LIVRO INT NOT NULL PRIMARY KEY,
    COD_TIT INT NOT NULL REFERENCES TITULO(COD_TIT),
    STATUS CHAR NOT NULL)

CREATE TABLE TITULO(
    COD_TIT INT NOT NULL PRIMARY KEY,
    DESCR VARCHAR NOT NULL)

CREATE TABLE TIPO_LIVRO(
    COD_TIPO INT NOT NULL PRIMARY KEY,
    DESCR_TIPO VARCHAR NOT NULL,
    QUANT_DIAS_LOCAC INT NOT NULL,
    VALOR_MULTA_DIA FLOAT NOT NULL
)

CREATE TABLE LOCACAO(
    COD_LOCACAO INT NOT NULL PRIMARY KEY,
    COD_CLI INT NOT NULL REFERENCES CLIENTE(COD_CLI),
    COD_LIVRO INT NOT NULL REFERENCES LIVRO(COD_LIVRO),
    DT_LOCACAO DATE NOT NULL,
    DT_PREV_DEVOL DATE NOT NULL,
    DT_DEVOLUCAO DATE NULL,
    MULTA FLOAT NULL)

INSERT INTO CLIENTE VALUES (1,'Marlysson')
INSERT INTO CLIENTE VALUES (2,'Maria')
INSERT INTO CLIENTE VALUES (3,'Marcelo')
INSERT INTO CLIENTE VALUES (4,'Marcos')

INSERT INTO TITULO VALUES (1,'Não conte à ninguém')
INSERT INTO TITULO VALUES (2,'À Prova de balas')
INSERT INTO TITULO VALUES (3,'A origem')
INSERT INTO TITULO VALUES (4,'Crime de Mestre')

INSERT INTO TIPO_LIVRO VALUES (1,'Cativo',1,1)
INSERT INTO TIPO_LIVRO VALUES (2,'Normal',7,1.50)
INSERT INTO TIPO_LIVRO VALUES (3,'Revista',2,1)

DROP TABLE TIPO_LIVRO
DROP TABLE TITULO
