# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.TextField(max_length=35)),
                ('complemento', models.TextField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='^\\d{5}-\\d{3}$')])),
                ('fone_residencial', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(regex='^\\d{4}-\\d{4}$')])),
                ('fone_trabalho', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(regex='^\\d{4}-\\d{4}$')])),
                ('renda_familiar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
