# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_auto_20170418_0232'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='fornecedor',
            table='fornecedor',
        ),
        migrations.AlterModelTable(
            name='itempedido',
            table='item_pedido',
        ),
        migrations.AlterModelTable(
            name='itemvenda',
            table='item_venda',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
        migrations.AlterModelTable(
            name='venda',
            table='venda',
        ),
    ]
