# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_auto_20170418_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_produto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venda',
            name='codigo_venda',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
