# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_auto_20170418_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_recebimento',
            field=models.DateField(),
        ),
    ]
