# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0005_auto_20170418_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='codigo_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedidos', to='venda.Pedido'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='codigo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_vendidos', to='venda.Produto'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='codigo_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='venda.Venda'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_pedidos', to='venda.Fornecedor'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='codigo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_compras', to='venda.Cliente'),
        ),
    ]
