# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0006_auto_20170421_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='codigo_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='venda.Pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='codigo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='venda.Produto'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='codigo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='venda.Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='venda.Fornecedor'),
        ),
    ]
